### ISSUE TITLE
Change branch `master` to `main`

### ISSUE THREAD

**Issue by vapurrmaid** [cdr/docs#245]
- [ ] Announce to team
- [ ] CI
- [ ] `cdr/m` submodule changes?

**Comment by jawnsy** [comment]
Totally agree with this! Just have to coordinate with the team as people will need to update their clones, and we would also need to update our GitHub Actions workflows

**Comment by vapurrmaid** [comment]
> Totally agree with this! Just have to coordinate with the team as people will need to update their clones, and we would also need to update our GitHub Actions workflows

May require evaluation of any steps in `cdr/m` submodule use

**Comment by jawnsy** [comment]
@vapurrmaid Also an excellent point, but tbh I'm cool with messing up the monorepo temporarily haha. I've also been pondering making this change to enterprise-helm, so this is a great test case for that :)

**Comment by jawnsy** [comment]
After changing enterprise-helm from master to main, it seems like everything just works. GitHub automatically redirects from the old branch (master) to the new branch (main). Submodules also seem unaffected, because the specified URL for many of these repositories do not include the branch name, so will use whatever GitHub returns as its default.

We announced our intention to do this to the team some time ago. People will need to manually rename their local branches but GitHub gives instructions for how to do that.
